### ISSUE TITLE
get error on 'eth.getPrivateTransaction'

### ISSUE THREAD

**Issue by laurivers** [Consensys-Incorporated/tessera#1522]
I deployed the sample contract code ('private-contract.js') successfully,and could call the `private.set() `and `private.get` successfully.
But when I called  eth.getPrivateTransaction, got error like this. 
```
> private.set(40,{from:eth.accounts[0],privateFor:["6CZ/yNFFCVXxPFFGKLDwo0h1HXSgJsWEH11ddZhRVlo="]});
"0x281125ea71298123c16574c8818732c20a1e4352292c4eafc4b63887499f55a4"
> eth.getPrivateTransaction('0x281125ea71298123c16574c8818732c20a1e4352292c4eafc4b63887499f55a4')
Error: invalid character '`' looking for beginning of value
	at web3.js:6355:37(47)
	at web3.js:5089:62(37)
	at <eval>:1:26(4)

> eth.getPrivateTransactionReceipt('0x281125ea71298123c16574c8818732c20a1e4352292c4eafc4b63887499f55a4')
Error: invalid character '`' looking for beginning of value
	at web3.js:6355:37(47)
	at web3.js:5089:62(37)
	at <eval>:1:33(4)
```

**Comment by baptiste-b-pegasys** [comment]
see https://github.com/ConsenSys/quorum/issues/1642
