### ISSUE TITLE
DNS communication not working in AWS 

### ISSUE THREAD

**Issue by preetgsanand** [Consensys-Incorporated/tessera#567]
When setting up tessera nodes with dns and tls off, the nodes are not able to communicate.

The error logs are below -

`
08:18:13
2018-11-21 08:18:13,870 INFO spawned: 'privacy_manager' with pid 70

08:18:14
2018-11-21 08:18:14,877 INFO success: privacy_manager entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

08:18:20
2018-11-21 08:18:20,473 DEBG 'privacy_manager' stdout output: 08:18:20.460 [main] INFO o.s.c.s.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@58ce9668: startup date [Wed Nov 21 08:18:20 UTC 2018]; root of context hierarchy

08:18:20
2018-11-21 08:18:20,569 DEBG 'privacy_manager' stdout output: 08:18:20.569 [main] INFO o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [tessera-spring.xml]

08:18:21
2018-11-21 08:18:21,112 DEBG 'privacy_manager' stdout output: 08:18:21.112 [main] INFO o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [tessera-core-spring.xml]

08:18:21
2018-11-21 08:18:21,876 DEBG 'privacy_manager' stdout output: 08:18:21.875 [main] INFO o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [tessera-grpc-spring.xml]

08:18:21
2018-11-21 08:18:21,905 DEBG 'privacy_manager' stdout output: 08:18:21.904 [main] INFO o.s.b.f.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [tessera-jaxrs-spring.xml]

08:18:22
2018-11-21 08:18:22,201 DEBG 'privacy_manager' stdout output: 08:18:22.201 [main] INFO o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring

08:18:22
2018-11-21 08:18:22,569 DEBG 'privacy_manager' stdout output: 08:18:22.569 [main] INFO o.s.o.j.LocalContainerEntityManagerFactoryBean - Building JPA container EntityManagerFactory for persistence unit 'tessera'

08:18:22
2018-11-21 08:18:22,883 DEBG 'privacy_manager' stdout output: 08:18:22.883 [main] INFO eclipselink.logging.all - EclipseLink, version: Eclipse Persistence Services - 2.7.3.v20180807-4be1041

08:18:23
2018-11-21 08:18:23,438 DEBG 'privacy_manager' stdout output: 08:18:23.438 [main] INFO eclipselink.logging.connection - tessera login successful

08:18:23
2018-11-21 08:18:23,540 DEBG 'privacy_manager' stdout output: 08:18:23.540 [main] WARN eclipselink.logging.ddl - Removing UNIQUE constraint definition from [ENCRYPTED_TRANSACTION.HASH] because it is also a primary key.

08:18:23
2018-11-21 08:18:23,548 DEBG 'privacy_manager' stdout output: 08:18:23.547 [main] INFO o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'tessera'

08:18:25
2018-11-21 08:18:25,354 DEBG 'privacy_manager' stdout output: 08:18:25.354 [main] INFO c.q.t.t.TesseraScheduledExecutor - Starting PartyInfoPoller

08:18:25
2018-11-21 08:18:25,356 DEBG 'privacy_manager' stdout output: 08:18:25.356 [main] INFO c.q.t.t.TesseraScheduledExecutor - Started PartyInfoPoller

08:18:25
2018-11-21 08:18:25,399 DEBG 'privacy_manager' stdout output: 08:18:25.398 [main] INFO c.q.t.t.TesseraScheduledExecutor - Starting SyncPoller

08:18:25
2018-11-21 08:18:25,401 DEBG 'privacy_manager' stdout output: 08:18:25.401 [main] INFO c.q.t.t.TesseraScheduledExecutor - Started SyncPoller

08:18:25
2018-11-21 08:18:25,643 DEBG 'privacy_manager' stdout output: 08:18:25.642 [main] INFO c.q.tessera.server.UnixSocketServer - Starting the Unix Domain Socket server

08:18:27
2018-11-21 08:18:27,704 DEBG 'privacy_manager' stdout output: 08:18:27.704 [main] INFO o.g.grizzly.servlet.WebappContext - Starting application [WebappContext] ...

08:18:27
2018-11-21 08:18:27,918 DEBG 'privacy_manager' stdout output: 08:18:27.918 [main] INFO o.g.grizzly.servlet.WebappContext - [WebappContext] Servlet [org.glassfish.jersey.servlet.ServletContainer] registered for url pattern(s) [[/*]].

08:18:27
2018-11-21 08:18:27,918 DEBG 'privacy_manager' stdout output: 08:18:27.918 [main] INFO o.g.grizzly.servlet.WebappContext - Application [WebappContext] is ready to service requests. Root: [].

08:18:27
2018-11-21 08:18:27,919 DEBG 'privacy_manager' stdout output: 08:18:27.918 [main] INFO c.quorum.tessera.server.JerseyServer - Starting http://0.0.0.0:9001

08:18:28
2018-11-21 08:18:28,114 DEBG 'privacy_manager' stdout output: 08:18:28.113 [main] INFO o.g.g.http.server.NetworkListener - Started listener bound to [0.0.0.0:9001]

08:18:28
2018-11-21 08:18:28,123 DEBG 'privacy_manager' stdout output: 08:18:28.123 [main] INFO o.g.grizzly.http.server.HttpServer - [HttpServer] Started.

08:18:28
2018-11-21 08:18:28,123 DEBG 'privacy_manager' stdout output: 08:18:28.123 [main] INFO c.quorum.tessera.server.JerseyServer - Started http://0.0.0.0:9001 08:18:28.123 [main] INFO c.quorum.tessera.server.JerseyServer - WADL http://0.0.0.0:9001/application.wadl

08:18:28
2018-11-21 08:18:28,178 DEBG 'privacy_manager' stdout output: 08:18:28.178 [jersey-server-managed-async-executor-0] INFO c.quorum.tessera.api.UpCheckResource - GET upcheck

08:18:30
2018-11-21 08:18:30,706 DEBG 'privacy_manager' stdout output: 08:18:30.705 [pool-5-thread-2] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: second.quorum.dev.info when connecting to http://second.quorum.dev.info:9001/

08:18:30
2018-11-21 08:18:30,714 DEBG 'privacy_manager' stdout output: 08:18:30.714 [pool-3-thread-1] ERROR c.q.tessera.node.PartyInfoPoller - Error thrown while executing poller. javax.ws.rs.ProcessingException: java.net.UnknownHostException: second.quorum.dev.info at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284) ~[tessera.jar:na] at org.glassfish.je

08:18:30
2018-11-21 08:18:30,715 DEBG 'privacy_manager' stdout output: 08:18:30.714 [pool-3-thread-1] ERROR c.q.t.t.TesseraScheduledExecutor - Error when executing action PartyInfoPoller

08:18:30
2018-11-21 08:18:30,716 DEBG 'privacy_manager' stdout output: 08:18:30.716 [pool-3-thread-1] ERROR c.q.t.t.TesseraScheduledExecutor - Error when executing action javax.ws.rs.ProcessingException: java.net.UnknownHostException: second.quorum.dev.info at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284) ~[tessera.jar:na] at org.glassfish.jersey.clien

08:18:30
2018-11-21 08:18:30,725 DEBG 'privacy_manager' stdout output: 08:18:30.724 [pool-5-thread-1] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: first.quorum.dev.info when connecting to http://first.quorum.dev.info:9001/

08:18:30
2018-11-21 08:18:30,758 DEBG 'privacy_manager' stdout output: 08:18:30.757 [pool-5-thread-2] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: first.quorum.dev.info when connecting to http://first.quorum.dev.info:9001/

08:18:30
2018-11-21 08:18:30,758 DEBG 'privacy_manager' stdout output: 08:18:30.757 [pool-5-thread-1] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: second.quorum.dev.info when connecting to http://second.quorum.dev.info:9001/

08:18:30
2018-11-21 08:18:30,817 DEBG 'privacy_manager' stdout output: 08:18:30.817 [pool-5-thread-1] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: first.quorum.dev.info when connecting to http://first.quorum.dev.info:9001/

08:18:30
2018-11-21 08:18:30,818 DEBG 'privacy_manager' stdout output: 08:18:30.817 [pool-5-thread-2] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: second.quorum.dev.info when connecting to http://second.quorum.dev.info:9001/

08:18:30
2018-11-21 08:18:30,877 DEBG 'privacy_manager' stdout output: 08:18:30.877 [pool-5-thread-1] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: second.quorum.dev.info when connecting to http://second.quorum.dev.info:9001/

08:18:30
2018-11-21 08:18:30,878 DEBG 'privacy_manager' stdout output: 08:18:30.878 [pool-5-thread-2] WARN com.quorum.tessera.sync.SyncPoller - Server error java.net.UnknownHostException: first.quorum.dev.info when connecting to http://first.quorum.dev.info:9001/

`

**Comment by prd-fox** [comment]
Hi Vince,

How is DNS set up in your AWS configuration?

For reference, I just set up 2 AWS instances and had them talk to each other using the default assigned public DNS names, and they communicated fine.

In your case, it looks like the underlying system is not able to resolve the hostname - are other services/applications on the machine able to connect to the host, or are you able to try? It doesn't seem like this issue would only affect Tessera.

**Comment by prd-fox** [comment]
@vince16 any update to this?

**Comment by Krish1979** [comment]
@vince16 - if this is till an issue , please reopen
