### ISSUE TITLE
mvn install command not finishing: upcheck not started error

### ISSUE THREAD

**Issue by samanshahmohamadi** [Consensys-Incorporated/tessera#613]
Hi
I'm trying to run tessera on an ubuntu 18 machine using java 8. When I run the command `JAVA_HOME=/usr/lib/jvm/java-8-oracle/ mvn install`, I get the following message. The command does not exit but keeps retrying over and over for different port numbers and nodes.
> http://localhost:50522/upcheck Not started.  
> Node C exited with code 2

**Comment by samanshahmohamadi** [comment]
Detailed logs:

> io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
        at com.quorum.tessera.grpc.p2p.TesseraGrpc$TesseraBlockingStub.getUpCheck(TesseraGrpc.java:218)
        at transaction.grpc.GrpcSteps.lambda$null$4(GrpcSteps.java:66)
        at ✽.all parties are running(features/transaction.feature:20)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:50520
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
        ... 11 more

**Comment by prd-fox** [comment]
There are extra logs inside `tests/acceptance-test/target/`, such as `nodeA.log` which should give a more detailed description as to why the node failed to boot. Are there any obvious errors inside there?

**Comment by samanshahmohamadi** [comment]
There are 5 node*.log files from A to E and all of them are empty. Do I need to start another component before starting tessera?

**Comment by prd-fox** [comment]
There is nothing else to start. What is the need to specify `JAVA_HOME`? Is Java not on the `$PATH` by default?

**Comment by samanshahmohamadi** [comment]
My default java version is 10, which tessera couldn't be installed with it. So I have to use the java8 to install it.

**Comment by prd-fox** [comment]
Ah right ok.
For the acceptance-tests (where this error occurred) it starts up instances of Tessera, but I am not sure if it would respect the JAVA_HOME passed in, and instead uses the system default, which could be failing.

A good way to validate would be to skip the tests to get the compiled jar (or download the one from the Releases page) and try and run it under JRE10.

Also, Java 11 should be fine to build with, which is one of the versions we use in our CI tool, so that is another possibility.

**Comment by samanshahmohamadi** [comment]
I followed the instruction, built tessera jar file (and also downloaded jar file from github), and when running jar file I get one line message: `javax/xml/bind/annotation/XmlElement`.
I tried to run jar file with java 8 and 10 and for both, same result.

**Comment by prd-fox** [comment]
Sorry for the delay.

Can you paste the output when running the downloaded jar under Java 8? I would only expect this issue to happen under Java 10.

**Comment by Krish1979** [comment]
Closing this issue. Please reopen if issue persists..
