### ISSUE TITLE
run the command mvn install, and the result has failure information 

### ISSUE THREAD

**Issue by jiebanghan** [Consensys-Incorporated/tessera#638]
hi ,please help me here, I am on windows10 and when I clone this repo and run the command mvn install, and the result has failure information  below. would you please give me some suggesion about how to solve it? thank you .

[INFO]-------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.quorum.tessera.io.FilesDelegateTest
[ERROR] Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.675 s <<< FAILURE! - in com.quorum.tessera.io.FilesDelegateTest
[ERROR] setPosixFilePermissions(com.quorum.tessera.io.FilesDelegateTest)  Time elapsed: 0.047 s  <<< ERROR!
java.lang.UnsupportedOperationException
        at com.quorum.tessera.io.FilesDelegateTest.setPosixFilePermissions(FilesDelegateTest.java:130)

[INFO] Running com.quorum.tessera.io.IOCallbackTest
11:20:49.081 [main] DEBUG com.quorum.tessera.io.IOCallback - null
java.io.IOException: OUCH
        at com.quorum.tessera.io.IOCallbackTest.doSomeIoStuffThatThrowsAnIoException(IOCallbackTest.java:30) ~[..%5C..%5C..%5C..%5C..%5C..%5Ctools%5Csrc%5Ctessera-master%5Cshared%5Ctarget%5Ctest-classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Cjunit%5Cjunit%5C4.12%5Cjunit-4.12.jar:4.12]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-junit4%5C3.0.0-M1%5Csurefire-junit4-3.0.0-M1.jar:3.0.0-M1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-junit4%5C3.0.0-M1%5Csurefire-junit4-3.0.0-M1.jar:3.0.0-M1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-junit4%5C3.0.0-M1%5Csurefire-junit4-3.0.0-M1.jar:3.0.0-M1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-junit4%5C3.0.0-M1%5Csurefire-junit4-3.0.0-M1.jar:3.0.0-M1]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-booter%5C3.0.0-M1%5Csurefire-booter-3.0.0-M1.jar:3.0.0-M1]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-booter%5C3.0.0-M1%5Csurefire-booter-3.0.0-M1.jar:3.0.0-M1]
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-booter%5C3.0.0-M1%5Csurefire-booter-3.0.0-M1.jar:3.0.0-M1]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) [..%5C..%5C..%5C..%5C.m2%5Crepository%5Corg%5Capache%5Cmaven%5Csurefire%5Csurefire-booter%5C3.0.0-M1%5Csurefire-booter-3.0.0-M1.jar:3.0.0-M1]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.617 s - in com.quorum.tessera.io.IOCallbackTest
[INFO] Running com.quorum.tessera.jaxb.JaxbCallbackTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.883 s - in com.quorum.tessera.jaxb.JaxbCallbackTest
[INFO] Running com.quorum.tessera.reflect.ReflectCallbackTest
11:20:50.679 [main] ERROR c.q.tessera.reflect.ReflectCallback - null
java.lang.ClassNotFoundException: null
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 s - in com.quorum.tessera.reflect.ReflectCallbackTest
[INFO] Running com.quorum.tessera.service.ServiceContainerTest
11:20:50.911 [main] WARN  c.q.tessera.service.ServiceContainer - Exception thrown : null While starting service Mock for Service, hashCode: 1498471420
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.214 s - in com.quorum.tessera.service.ServiceContainerTest
[INFO] Running com.quorum.tessera.ServiceLoaderUtilTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in com.quorum.tessera.ServiceLoaderUtilTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   FilesDelegateTest.setPosixFilePermissions:130 ? UnsupportedOperation
[INFO]
[ERROR] Tests run: 23, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] tessera 0.9-SNAPSHOT ............................... SUCCESS [  4.777 s]
[INFO] argon2 ............................................. SUCCESS [ 12.940 s]
[INFO] tests .............................................. SUCCESS [  0.533 s]
[INFO] test-util .......................................... SUCCESS [  0.637 s]
[INFO] shared ............................................. FAILURE [  7.652 s]
[INFO] service-locator .................................... SKIPPED
[INFO] service-locator-api ................................ SKIPPED
[INFO] encryption ......................................... SKIPPED
[INFO] encryption-api ..................................... SKIPPED
[INFO] encryption-jnacl ................................... SKIPPED
[INFO] config ............................................. SKIPPED
[INFO] security ........................................... SKIPPED
[INFO] server ............................................. SKIPPED
[INFO] server-api ......................................... SKIPPED
[INFO] jersey-server ...................................... SKIPPED
[INFO] jaxrs-client ....................................... SKIPPED
[INFO] key-vault .......................................... SKIPPED
[INFO] key-vault-api ...................................... SKIPPED
[INFO] key-generation ..................................... SKIPPED
[INFO] config-cli ......................................... SKIPPED
[INFO] key-pair-converter ................................. SKIPPED
[INFO] enclave ............................................ SKIPPED
[INFO] enclave-api ........................................ SKIPPED
[INFO] tessera-core ....................................... SKIPPED
[INFO] jaxrs-service ...................................... SKIPPED
[INFO] grpc ............................................... SKIPPED
[INFO] grpc-api ........................................... SKIPPED
[INFO] grpc-service ....................................... SKIPPED
[INFO] grpc-server ........................................ SKIPPED
[INFO] unix-socket-server ................................. SKIPPED
[INFO] service-locator-spring ............................. SKIPPED
[INFO] azure-key-vault .................................... SKIPPED
[INFO] hashicorp-key-vault ................................ SKIPPED
[INFO] tessera-app ........................................ SKIPPED
[INFO] config-migration ................................... SKIPPED
[INFO] acceptance-test .................................... SKIPPED
[INFO] jmeter-test ........................................ SKIPPED
[INFO] websockets-server .................................. SKIPPED
[INFO] encryption-kalium .................................. SKIPPED
[INFO] data-migration ..................................... SKIPPED
[INFO] ddls ............................................... SKIPPED
[INFO] enclave-server ..................................... SKIPPED
[INFO] enclave-jaxrs ...................................... SKIPPED
[INFO] enclave-websockets ................................. SKIPPED
[INFO] tessera-sync 0.9-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.300 s
[INFO] Finished at: 2019-02-22T11:20:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project shared: There are test failures.
[ERROR]
[ERROR] Please refer to C:\tools\src\tessera-master\shared\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :shared
PS C:\tools\src\tessera-master>

**Comment by jiebanghan** [comment]
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by jiebanghan** [comment]
mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: C:\tools\apache-maven-3.5.4-bin\apache-maven-3.5.4\bin\..
Java version: 1.8.0_77, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_77\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by prd-fox** [comment]
The issue looks like a permissions issue. The test tries to assign POSIX permissions, which don't exist in Windows, and an error gets thrown.

Until a solution is merged, the best thing to do would be to skip the tests during the build process by running `mvn clean install -DskipTests=true`.
Note that the tests exist because some parts of the code do try to assign POSIX file permissions, so you may find those features throw the same issue on Windows environments, e.g. creating new keys.
