### ISSUE TITLE
Could not start with setting SSL

### ISSUE THREAD

**Issue by knakagoe1** [Consensys-Incorporated/tessera#848]
Tessera:v0.9.2
openjdk:java 8
OS:Ubuntu 18.04

Hello.
I got the error below when I started tessera nodes.There are 2 tessera nodes.
`
15:52:16.464 [pool-2-thread-1] ERROR c.q.tessera.node.PartyInfoPoller - Error thrown while executing poller.
javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: This address has been associated with a different certificate
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:284) ~[tessera.jar:na]
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278) ~[tessera.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753) ~[tessera.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[tessera.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[tessera.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:229) ~[tessera.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414) ~[tessera.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752) ~[tessera.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445) ~[tessera.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351) ~[tessera.jar:na]
        at com.quorum.tessera.client.PostDelegate.doPost(PostDelegate.java:39) ~[tessera.jar:na]
        at com.quorum.tessera.client.RestP2pClient.getPartyInfo(RestP2pClient.java:23) ~[tessera.jar:na]
        at com.quorum.tessera.node.PartyInfoPoller.pollSingleParty(PartyInfoPoller.java:75) [tessera.jar:na]
        at com.quorum.tessera.node.PartyInfoPoller.lambda$run$1(PartyInfoPoller.java:54) [tessera.jar:na]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_222]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_222]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:1.8.0_222]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:1.8.0_222]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_222]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[na:1.8.0_222]
        at com.quorum.tessera.node.PartyInfoPoller.run(PartyInfoPoller.java:57) [tessera.jar:na]
        at com.quorum.tessera.threading.TesseraScheduledExecutor.lambda$start$0(TesseraScheduledExecutor.java:50) ~[tessera.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_222]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: This address has been associated with a different certificate
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_222]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946) ~[na:1.8.0_222]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316) ~[na:1.8.0_222]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310) ~[na:1.8.0_222]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639) ~[na:1.8.0_222]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223) ~[na:1.8.0_222]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037) ~[na:1.8.0_222]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965) ~[na:1.8.0_222]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064) ~[na:1.8.0_222]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[na:1.8.0_222]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[na:1.8.0_222]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[na:1.8.0_222]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_222]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340) ~[na:1.8.0_222]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315) ~[na:1.8.0_222]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264) ~[na:1.8.0_222]
        at org.glassfish.jersey.client.internal.HttpUrlConnector.lambda$_apply$0(HttpUrlConnector.java:382) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:195) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:189) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:208) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:295) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.ByteArrayProvider.writeTo(ByteArrayProvider.java:97) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.ByteArrayProvider.writeTo(ByteArrayProvider.java:61) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163) ~[tessera.jar:na]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135) ~[tessera.jar:na]
        at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:516) ~[tessera.jar:na]
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:498) ~[tessera.jar:na]
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:384) ~[tessera.jar:na]
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:282) ~[tessera.jar:na]
        ... 32 common frames omitted
Caused by: java.security.cert.CertificateException: This address has been associated with a different certificate
        at com.quorum.tessera.ssl.trust.TrustOnFirstUseManager.checkTrusted(TrustOnFirstUseManager.java:45) ~[tessera.jar:na]
        at com.quorum.tessera.ssl.trust.TrustOnFirstUseManager.checkServerTrusted(TrustOnFirstUseManager.java:24) ~[tessera.jar:na]
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1099) ~[na:1.8.0_222]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621) ~[na:1.8.0_222]
        ... 59 common frames omitted
`

configulation json file is below
[tessera01_TLS.json.txt](https://github.com/jpmorganchase/tessera/files/3480308/tessera01_TLS.json.txt)
[tessera02_TLS.json.txt](https://github.com/jpmorganchase/tessera/files/3480362/tessera02_TLS.json.txt)

**Comment by namtruong** [comment]
Hi,

The error seems to indicate that the node has been restarted with a different certificate. If this was the case what you can do is empty or delete the knownClientsFile/knownServersFile where the old certificates are stored against the host.

**Comment by knakagoe1** [comment]
@namtruong 
Thank you so much. 
I resolved the problem when 2 nodes put in the same virtual network and using private IP address but got another error when each node put in the diffrent virtual network and using public IP address.

``
2019-09-05 17:57:07.399 [pool-3-thread-1] WARN  c.q.t.partyinfo.PartyInfoPoller - Error javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names matching IP address xx.xx.xx.xx found when connecting to https://xx.xx.xx.xx:9001/
``
How could I solve this error?
